image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      touch /tmp/.npm-lock
      pnpm install
      rm /tmp/.npm-lock
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: |
      cd apps/api 
      pnpm seed 
      echo cron=1 > .env
      cd ../game-server
      echo cron=1
      cd ../../
      pnpm dev --filter @bgs/api --filter @bgs/game-server --filter @bgs/web --filter @bgs/admin

ports:
  - port: 8615
    onOpen: open-preview
  - port: 8613
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - octref.vetur@0.32.0:03mwRhlVpWDul4qBChcVUA==
