version: "3.9"
services:
  mongo:
    image: "mongo:4.4"
  api:
    build:
      context: .
      dockerfile: ./api-node/Dockerfile
    ports:
      - "50801:50801"
      - "50803:50803"
      - "50804:50804"
    environment:
      - dbUrl="mongodb://mongo:27017/admin"
  game-server:
    build:
      context: .
      dockerfile: ./game-server/Dockerfile
    ports:
      - "50802:50802"
    environment:
      - dbUrl="mongodb://mongo:27017/admin"
