version: "3.9"
services:
  mongo:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
  api:
    build:
      context: .
      dockerfile: ./packages/server/api-node/Dockerfile
    ports:
      - "50801:50801"
      - "50802:50802"
      - "50804:50804"
    environment:
      - "dbUrl=mongodb://mongo:27017/admin"
      - "listenHost=::"
      - "cron=1"
  game-server:
    build:
      context: .
      dockerfile: ./packages/server/game-server/Dockerfile
    ports:
      - "50803:50803"
    environment:
      - "dbUrl=mongodb://mongo:27017/admin"
      - "listenHost=::"
      - "cron=1"
    volumes:
      - games:/usr/src/app/games
volumes:
  games:
