packages:
  - "packages/docs"
  - "packages/server/api-node"
  - "packages/server/game-server"
  - "packages/shared/types"
  - "packages/shared/models"
  - "packages/web/admin-app"
  - "packages/web/webapp-svelte"
