name: Game-Server
on:
  push:
    paths:
      - ".forgejo/workflows/game-server.yml"
      - "apps/game-server/**"
      - "packages/**"
    branches:
      - main
  pull_request:
    paths:
      - ".forgejo/workflows/game-server.yml"
      - "apps/game-server/**"
      - "packages/**"

defaults:
  run:
    working-directory: apps/game-server

jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: pnpm install --filter {./}...
      - run: pnpm run lint-check
      - run: pnpm run tsc
