name: Utils
on:
  push:
    paths:
      - ".forgejo/workflows/utils.yml"
      - "packages/utils/**"
    branches:
      - main
  pull_request:
    paths:
      - ".forgejo/workflows/utils.yml"
      - "packages/utils/**"

defaults:
  run:
    working-directory: packages/utils

jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: pnpm install --filter {./}...
      - run: pnpm run lint-check
      - run: pnpm run tsc
      - run: pnpm test
