// Curated emoji set for the chat picker, with English names/keywords for search
// (searching English is fine — Discord does the same). Imported ONLY by
// ChatEmojiPicker.svelte, so it stays in the picker's lazy chunk.

export type EmojiEntry = [emoji: string, keywords: string];

export const EMOJI_CATEGORIES: { id: string; icon: string; emoji: EmojiEntry[] }[] = [
	{
		id: "smileys",
		icon: "😀",
		emoji: [
			["😀", "grinning face happy smile"],
			["😃", "grinning face big eyes happy"],
			["😄", "grinning face smiling eyes happy"],
			["😁", "beaming face grin"],
			["😆", "grinning squinting laugh haha"],
			["😅", "grinning sweat relief phew"],
			["😂", "face with tears of joy laugh lol funny"],
			["🤣", "rolling on the floor laughing rofl"],
			["🙂", "slightly smiling face"],
			["😉", "winking face wink"],
			["😊", "smiling face blush happy"],
			["😇", "smiling face halo innocent angel"],
			["🥰", "smiling face with hearts love adore"],
			["😍", "heart eyes love"],
			["😘", "face blowing a kiss"],
			["😜", "winking face with tongue playful"],
			["🤪", "zany face crazy goofy"],
			["🤔", "thinking face hmm ponder"],
			["🤨", "face with raised eyebrow skeptical suspicious"],
			["😐", "neutral face meh"],
			["😏", "smirking face smug"],
			["🙄", "face with rolling eyes"],
			["😬", "grimacing face awkward"],
			["😴", "sleeping face zzz tired"],
			["🤯", "exploding head mind blown"],
			["😳", "flushed face embarrassed"],
			["🥺", "pleading face puppy eyes please"],
			["😢", "crying face sad tear"],
			["😭", "loudly crying face sob"],
			["😡", "pouting face angry mad rage"],
			["😱", "face screaming in fear scared"],
			["🥳", "partying face celebration party"],
		],
	},
	{
		id: "people",
		icon: "👍",
		emoji: [
			["👍", "thumbs up like yes approve"],
			["👎", "thumbs down dislike no"],
			["👏", "clapping hands applause bravo"],
			["🙌", "raising hands hooray celebration"],
			["🤝", "handshake deal agreement"],
			["🙏", "folded hands please thanks pray"],
			["💪", "flexed biceps strong muscle"],
			["🤞", "crossed fingers luck hope"],
			["✌️", "victory hand peace"],
			["🤘", "sign of the horns rock"],
			["👌", "ok hand perfect"],
			["🤌", "pinched fingers chef kiss"],
			["👋", "waving hand hello goodbye"],
			["✋", "raised hand stop high five"],
			["👆", "backhand index pointing up"],
			["👇", "backhand index pointing down"],
			["👈", "backhand index pointing left"],
			["👉", "backhand index pointing right"],
			["🫡", "saluting face respect"],
			["🤷", "person shrugging shrug dunno"],
			["🤦", "person facepalming facepalm"],
			["🧠", "brain smart clever think"],
			["👀", "eyes look watch see"],
			["💅", "nail polish sassy"],
		],
	},
	{
		id: "nature",
		icon: "🐶",
		emoji: [
			["🐶", "dog face puppy"],
			["🐱", "cat face kitten"],
			["🐭", "mouse face"],
			["🐹", "hamster face"],
			["🐰", "rabbit face bunny"],
			["🦊", "fox face"],
			["🐻", "bear face"],
			["🐼", "panda face"],
			["🐨", "koala face"],
			["🐯", "tiger face"],
			["🦁", "lion face"],
			["🐮", "cow face"],
			["🐷", "pig face"],
			["🐸", "frog face"],
			["🐵", "monkey face"],
			["🐔", "chicken"],
			["🐧", "penguin"],
			["🦉", "owl"],
			["🦄", "unicorn"],
			["🐝", "honeybee bee"],
			["🦋", "butterfly"],
			["🌸", "cherry blossom flower"],
			["🌳", "deciduous tree"],
			["🌈", "rainbow"],
		],
	},
	{
		id: "food",
		icon: "🍕",
		emoji: [
			["🍎", "red apple fruit"],
			["🍌", "banana fruit"],
			["🍉", "watermelon fruit"],
			["🍇", "grapes fruit"],
			["🍓", "strawberry fruit"],
			["🍒", "cherries fruit"],
			["🍑", "peach fruit"],
			["🍍", "pineapple fruit"],
			["🥑", "avocado"],
			["🍕", "pizza slice"],
			["🍔", "hamburger burger"],
			["🍟", "french fries chips"],
			["🌭", "hot dog"],
			["🍿", "popcorn movie"],
			["🧀", "cheese wedge"],
			["🥐", "croissant"],
			["🍞", "bread loaf"],
			["🍪", "cookie biscuit"],
			["🎂", "birthday cake"],
			["🍰", "shortcake cake dessert"],
			["🍫", "chocolate bar"],
			["☕", "hot beverage coffee tea"],
			["🍺", "beer mug"],
			["🥂", "clinking glasses champagne cheers toast"],
		],
	},
	{
		id: "activities",
		icon: "🎲",
		emoji: [
			["🎲", "game die dice roll board game"],
			["♟️", "chess pawn board game"],
			["🃏", "joker playing card"],
			["🎴", "flower playing cards hanafuda"],
			["🀄", "mahjong red dragon tile"],
			["🧩", "puzzle piece jigsaw"],
			["🎯", "bullseye direct hit darts target"],
			["🎮", "video game controller gaming"],
			["🕹️", "joystick arcade"],
			["🎳", "bowling strike"],
			["🏆", "trophy winner champion victory"],
			["🥇", "gold medal first place"],
			["🥈", "silver medal second place"],
			["🥉", "bronze medal third place"],
			["⚽", "soccer ball football"],
			["🏀", "basketball"],
			["🏈", "american football"],
			["⚾", "baseball"],
			["🎾", "tennis"],
			["🏐", "volleyball"],
			["🎱", "pool 8 ball billiards"],
			["🏓", "ping pong table tennis"],
			["⛳", "flag in hole golf"],
			["🎪", "circus tent"],
		],
	},
	{
		id: "objects",
		icon: "💡",
		emoji: [
			["⌛", "hourglass done time wait"],
			["⏰", "alarm clock time"],
			["💡", "light bulb idea"],
			["🔥", "fire hot lit flame"],
			["⭐", "star favorite"],
			["🌟", "glowing star shining"],
			["✨", "sparkles magic shiny"],
			["⚡", "high voltage lightning zap thunder"],
			["💥", "collision boom explosion"],
			["❄️", "snowflake cold winter"],
			["🎁", "wrapped gift present"],
			["🎈", "balloon party"],
			["🎉", "party popper celebration tada congratulations"],
			["🎊", "confetti ball celebration"],
			["📌", "pushpin pin location"],
			["✏️", "pencil write draw"],
			["📖", "open book read"],
			["🔑", "key unlock"],
			["🔒", "locked padlock secure"],
			["🛡️", "shield defense protect"],
			["⚔️", "crossed swords battle fight war"],
			["🔮", "crystal ball fortune magic"],
			["💎", "gem stone diamond jewel"],
			["🧭", "compass navigation direction"],
		],
	},
	{
		id: "symbols",
		icon: "❤️",
		emoji: [
			["❤️", "red heart love"],
			["🧡", "orange heart"],
			["💛", "yellow heart"],
			["💚", "green heart"],
			["💙", "blue heart"],
			["💜", "purple heart"],
			["🖤", "black heart"],
			["🤍", "white heart"],
			["💔", "broken heart heartbreak"],
			["💕", "two hearts love"],
			["💯", "hundred points perfect score"],
			["✅", "check mark button done yes correct"],
			["❌", "cross mark no wrong incorrect"],
			["⭕", "hollow red circle correct"],
			["❗", "red exclamation mark important"],
			["❓", "red question mark"],
			["⚠️", "warning caution"],
			["🚫", "prohibited forbidden banned no"],
			["➕", "plus sign add"],
			["➖", "minus sign subtract"],
			["🔁", "repeat loop again"],
			["🆗", "ok button okay"],
			["🆒", "cool button"],
			["🏁", "chequered flag finish race done"],
		],
	},
];
