name: All
on: [pull_request, push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run prettier-check
