name: Api-Node
on:
  push:
    paths:
      - ".github/workflows/api-node.yml"
      - "api-node"
      - "site-lib"
  pull_request:
    paths:
      - ".github/workflows/api-node.yml"
      - "api-node"
      - "site-lib"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.1
      - run: cd api-node
      - run: pnpm install
      - run: pnpm run lint-check
      - run: pnpm run tsc
      - run: pnpm run test
