name: Api-Node
on:
  push:
    paths:
      - ".github/workflows/api-node.yml"
      - "packages/server/api-node/**"
      - "packages/shared/**"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/api-node.yml"
      - "packages/server/api-node/**"
      - "packages/shared/**"

defaults:
  run:
    working-directory: packages/server/api-node

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - run: npm install -g pnpm
      - run: pnpm install --filter {./}...
      - run: pnpm run lint-check
      - run: pnpm run tsc
      - run: pnpm run test
