name: Api-Node
on:
  push:
    paths:
      - ".github/workflows/api-node.yml"
      - "api-node/**"
      - "site-lib/**"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/api-node.yml"
      - "api-node/**"
      - "site-lib/**"

defaults:
  run:
    working-directory: api-node

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.1
      - run: pnpm install
      - run: pnpm run lint-check
      - run: pnpm run tsc
      - run: pnpm run test
