name: Api-Node
on:
  push:
    paths:
      - ".github/workflows/api.yml"
      - "apps/api/**"
      - "packages/**"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/api.yml"
      - "apps/api/**"
      - "packages/**"

defaults:
  run:
    working-directory: apps/api

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - run: corepack enable
      - run: pnpm install --filter {./}... --filter ../..
      - run: pnpm run lint-check
      - run: pnpm install --filter "@bgs/models"
      - run: pnpm install --filter "@bgs/utils"
      - run: pnpm run type-check
      - run: pnpm run test
