name: Game-Server
on:
  push:
    paths:
      - ".github/workflows/game-server.yml"
      - "packages/server/game-server/**"
      - "packages/shared/**"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/game-server.yml"
      - "packages/server/game-server/**"
      - "packages/shared/**"

defaults:
  run:
    working-directory: packages/server/game-server

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g pnpm
      - run: pnpm install --filter {./}...
      - run: pnpm run lint-check
      - run: pnpm run tsc
