name: Game-Server
on:
  push:
    paths:
      - ".github/workflows/game-server.yml"
      - "game-server"
      - "site-lib"
  pull_request:
    paths:
      - ".github/workflows/game-server.yml"
      - "game-server"
      - "site-lib"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.1
      - run: cd game-server
      - run: pnpm install
      - run: pnpm run lint-check
      - run: pnpm run tsc
