name: Game-Server
on:
  push:
    paths:
      - ".github/workflows/game-server.yml"
      - "apps/game-server/**"
      - "packages/**"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/game-server.yml"
      - "apps/game-server/**"
      - "packages/**"

defaults:
  run:
    working-directory: apps/game-server

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: corepack enable
      - run: pnpm install --filter {./}...
      - run: pnpm run lint-check
      - run: pnpm install --filter "@bgs/models"
      - run: pnpm run tsc
