name: Game-Server
on:
  push:
    paths:
      - ".github/workflows/utils.yml"
      - "packages/shared/utils/**"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/utils.yml"
      - "packages/shared/utils/**"

defaults:
  run:
    working-directory: packages/shared/utils

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 6.14.3
      - run: pnpm install --filter {./}...
      - run: pnpm test
